# Generated by Django 4.1.7 on 2023-05-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FLEX', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='RollNo',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
