# Generated by Django 4.1.7 on 2023-05-14 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('PfpUrl', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.CharField(max_length=512)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.teacher')),
            ],
        ),
    ]
