# Generated by Django 4.1.7 on 2023-04-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Attendace',
            new_name='Attendance',
        ),
    ]
