# Generated by Django 4.1.7 on 2023-04-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_rename_attendace_student_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Attendance',
        ),
    ]
